// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://intcujjoeornspjvdjak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImludGN1ampvZW9ybnNwanZkamFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDQ1MzksImV4cCI6MjA2NjMyMDUzOX0.gUFhCD5AkH_Ltij1cbVQ7j-uo0CjvfTFsAtZNJIfkYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});