// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://intcujjoeornspjvdjak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImludGN1ampvZW9ybnNwanZkamFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDQ1MzksImV4cCI6MjA2NjMyMDUzOX0.gUFhCD5AkH_Ltij1cbVQ7j-uo0CjvfTFsAtZNJIfkYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Auth helper functions
export async function signUp({ email, password }: { email: string; password: string }) {
  return supabase.auth.signUp({ email, password });
}

export async function signIn({ email, password }: { email: string; password: string }) {
  return supabase.auth.signInWithPassword({ email, password });
}

export async function signOut() {
  return supabase.auth.signOut();
}

export async function resetPassword(email: string) {
  return supabase.auth.resetPasswordForEmail(email);
}

export function getUser() {
  return supabase.auth.getUser();
}

// Create a profile for a new user
export async function createProfile({ id, role = 'student', full_name = '', avatar_url = '' }: { id: string, role?: string, full_name?: string, avatar_url?: string }) {
  return supabase.from('profiles').insert([{ id, role, full_name, avatar_url }]);
}

// Fetch a profile by user id
export async function getProfileById(id: string) {
  return supabase.from('profiles').select('*').eq('id', id).single();
}